---
- hosts: testredhat
  become: yes
  tasks:
    - name: create an empty file
      file: 
        path: /home/ansible/readme.txt
        state: touch 
    - name: create a simlink
      file:
       src: /home/ansible/readme.txt
       dest: /home/ansible/readmecopy.txt
       state: link
    - name: create a directory
      file:
       path: /home/ansible/testdr
       state: directory
    - name: downloading a file
      file:
       url: https://war-jar-files.s3-us-west-2.amazonaws.com/gameoflife.war
       dest: /home/ansible/ansible.war
       



