---
- hosts: testredhat
  become: yes
  tasks:
    - name: create an empty file
      file: 
        path: /home/ansible/readme.txt
        state: touch 
    - name: create a simlink
      file:
       src: /home/ansible/readme.txt
       dest: /home/ansible/readmecopy.txt
       state: link

