---
- hosts: all
  become: yes
  vars:
    package_name: git
  tasks:
    - name: git installation
      yum:
        name: "{{ package_name }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: tree install
      yum:
        name: tree
        state: present
      when: ansible_facts['os_family'] == "CentOS"
