---
- hosts: all
  become: yes
  vars:
    package_name: git
  tasks:
    - name: git installation
      apt:
        name: {{ package_name }}
        update-cache: yes
        state: present
      when: ansible_facts['os_family'] == "CentOS"
    - name: tree install
      apt:
        name: tree
        update-cache: yes
        state: present
      when: ansible_facts['os_family'] == "CentOS"
---
