---
- hosts: webserver
  become: yes
  tasks:
    - name: fail for other  platforms
      fail:
        msg: This is not supported OS
      when:
        - ansible_os_family != "RedHat"
    - name: install httpd in Redhat
      yum:
        name: httpd
        state: present
      notify:
      - restart of httpd service
    - name: install php modules
      yum:
        name: "{{ item }}"
        state: present
      loop:
      - php
      - php-pdo
      notify:
      - restart of httpd service
  handlers:
    - name: restart of httpd service
      service:
        name: httpd
        enable: yes
        state: restarted
