---
- hosts: webserver
  become: yes
  tasks:
      - name: install httpd
        yum:
          name: httpd
          state: present
          update_cache: yes
        notify:
        - restart of httpd service
      - name: install php modules
        yum:
         name: "{{ item }}"
         state: present
        loop:
        - php
        - pho-cli
        notify:
        - restart of httpd service
  handlers:
      - name: restart of httpd service
        service:
         name: httpd
         enabled: yes
         state: restarted
      
