---
- hosts: all
  become: yes
  tasks:
    - name: uninstall git or tree
      yum:
        name: "{{ item }}"
        state: present
      loop:
      - git
      - tree
      when: ansible_facts['os_family'] == "CentOS"
    - name: uninstall git or tree
      apt:
        name: "{{ item }}"
        state: present
      loop:
      - git
      - tree
      when: ansible_facts['os_family'] == "Debian"