---
- hosts: Webserver
  become: yes
  tasks:
    - name: install apache
      package:
        name: httpd
        state: present
    - name: service start
      service:
        name: httpd
        enabled: yes
        state: started
