---
- hosts: webserver
  become: yes
  tasks:
    - name: install apache
      package: 
        name: apache
        state: present
    - name: restart service
      service:
        name: httpd
        enabled: yes
        state: restarted

    

      